AppquariumBundle\Entity\Accessory:
    type: entity
    table: accessory
    indexes:
        fk_accessory_aquarium1_idx:
            columns:
                - aquarium_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        price:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: ''
        date:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        aquarium:
            targetEntity: Aquarium
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                aquarium_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
