AppquariumBundle\Entity\Aquarium:
    type: entity
    repositoryClass: AppquariumBundle\Entity\AquariumRepository
    table: aquarium
    indexes:
        fk_aquariums_users1_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        alias:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        waterType:
            type: string
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: water_type
        capacity:
            type: smallint
            nullable: true
            unsigned: false
            comment: ''
        avatar:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
