AppquariumBundle\Entity\WaterParamMeasure:
    type: entity
    repositoryClass: AppquariumBundle\Entity\WaterParamMeasureRepository
    table: water_param_measure
    indexes:
        fk_param_log_aquariums1_idx:
            columns:
                - aquarium_id
        fk_water_param_measure_aquarium_param1_idx:
            columns:
                - aquarium_param_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: decimal
            nullable: true
            precision: 10
            scale: 4
            comment: ''
        date:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    manyToOne:
        paramValueRange:
            targetEntity: ParamValueRange
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                param_value_range_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
