admin.users_list:
    path: /
    defaults: { _controller: appquarium.admin.users.controller:userListAction }
    methods: [GET]
admin.user.remove:
    path: /user/remove
    defaults: { _controller: appquarium.admin.users.controller:removeUserAction }
    methods: [POST]
admin.user.update:
    path: /user/update
    defaults: { _controller: appquarium.admin.users.controller:updateUserAction }
    methods: [POST]
admin.send_user_message:
    path: /send
    defaults: { _controller: appquarium.admin.users.controller:sendMessageAction }
    methods: [POST]
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
admin.newsletter:
    path: /newsletter
    defaults: { _controller: appquarium.admin.newsletter.controller:newsletterAction }
    methods: [GET]
admin.send_newsletter:
    path: /newsletter/send
    defaults: { _controller: appquarium.admin.newsletter.controller:sendNewsletterAction }
    methods: [POST]
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
admin.parameters:
    path: /parameters
    defaults: { _controller: appquarium.admin.solutions.controller:parameterListAction }
    methods: [GET]
admin.store.parameters:
   path: /parameters/store
   defaults: { _controller: appquarium.admin.solutions.controller:storeParametersAction }
   methods: [POST]